project_id = "urcywqpdbyrduzfzvvne"

[functions.ai-assistant]
verify_jwt = true

[functions.green-chatbot]
verify_jwt = false

[functions.send-line-notification]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.evaluate-application]
verify_jwt = false

[functions.suggest-position]
verify_jwt = false

[functions.send-message-to-applicant]
verify_jwt = true

[functions.setup-initial-admin]
verify_jwt = true

[functions.process-email-queue]
verify_jwt = false

[functions.teams]
verify_jwt = false

[functions.parse-cv]
verify_jwt = true