project_id = "urcywqpdbyrduzfzvvne"

[functions.green-chatbot]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.evaluate-application]
verify_jwt = false

[functions.suggest-position]
verify_jwt = false

[functions.setup-initial-admin]
verify_jwt = false
