project_id = "urcywqpdbyrduzfzvvne"

[functions.green-chatbot]
verify_jwt = false

[functions.send-application-email]
verify_jwt = false

[functions.evaluate-application]
verify_jwt = false

[functions.suggest-position]
verify_jwt = false

[functions.send-message-to-applicant]
verify_jwt = true

[functions.setup-initial-admin]
verify_jwt = true
